# Generated by TanukiParser - Namespace: SonicEther
from enum import Enum, auto

class TokenType(Enum):
    OPEN_BRACKET = auto()
    CLOSE_BRACKET = auto()
    OPEN_BRACKET_FULL = auto()
    CLOSE_BRACKET_FULL = auto()
    OPEN_PAREN = auto()
    CLOSE_PAREN = auto()
    OPEN_PAREN_FULL = auto()
    CLOSE_PAREN_FULL = auto()
    ANGLE_LEFT = auto()
    ANGLE_RIGHT = auto()
    CHORD_MARK = auto()
    TEXT = auto()
    NL = auto()

class LyricsParser:
    def __init__(self, tokenizer, tag_handler=None, ruby_handler=None):
        self.tokenizer = tokenizer
        self.token = None
        self.results = []
        self.tag_buffer = []
        self.tag_handler = tag_handler
        self.ruby_handler = ruby_handler
    
    def lyrics(self):
        ret_val_0 = None
        ret_val = True
        ret_val_0 = None
        while (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL):
            ret_val_0 = self.element()
        return ret_val
    
    def element(self):
        ret_val_0 = None
        ret_val = True
        ret_val_0 = None
        checkpoint_idx = self.tokenizer.index
        checkpoint_tok = self.token
        ret_val_0 = self.tag()
        if ret_val_0 is not None:
            ret_val = ret_val_0
        else:
            self.tokenizer.index = checkpoint_idx
            self.token = checkpoint_tok
            ret_val_0 = self.text_content()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.other_char()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    self.tokenizer.index = checkpoint_idx
                    self.token = checkpoint_tok
                    ret_val_0 = self.newline()
                    if ret_val_0 is not None:
                        ret_val = ret_val_0
                    else:
                        ret_val = None
        return ret_val
    
    def tag(self):
        ret_val_0 = None
        ret_val = True
        ret_val_0 = None
        match self.token.token_type:
            case TokenType.OPEN_BRACKET:
                ret_val_0 = self.bracket_tag()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                ret_val_0 = self.bracket_full_tag()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                ret_val_0 = self.paren_tag()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                ret_val_0 = self.paren_full_tag()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                ret_val_0 = self.angle_tag()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                ret_val_0 = self.chord_line()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def bracket_tag(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.OPEN_BRACKET):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["["]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL) or (self.token.token_type == TokenType.OPEN_BRACKET):
            checkpoint_idx = self.tokenizer.index
            checkpoint_tok = self.token
            ret_val_0 = self.bracket_inner()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.bracket_tag()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    ret_val = None
                    break
        if (self.token.token_type != TokenType.CLOSE_BRACKET):
            self.tag_buffer = old_buffer
            return None
        self.token = self.tokenizer.get_token()
        self.tag_buffer.append("]")
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "B"))
        return ret_val
    
    def bracket_full_tag(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["［"]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL):
            checkpoint_idx = self.tokenizer.index
            checkpoint_tok = self.token
            ret_val_0 = self.bracket_full_inner()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.bracket_full_tag()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    ret_val = None
                    break
        if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
            self.tag_buffer = old_buffer
            return None
        self.token = self.tokenizer.get_token()
        self.tag_buffer.append("］")
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "B"))
        return ret_val
    
    def paren_tag(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.OPEN_PAREN):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["("]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL) or (self.token.token_type == TokenType.OPEN_PAREN):
            checkpoint_idx = self.tokenizer.index
            checkpoint_tok = self.token
            ret_val_0 = self.paren_inner()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.paren_tag()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    ret_val = None
                    break
        if (self.token.token_type != TokenType.CLOSE_PAREN):
            self.tag_buffer = old_buffer
            return None
        self.token = self.tokenizer.get_token()
        self.tag_buffer.append(")")
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "P"))
        elif self.ruby_handler: self.results.append(self.ruby_handler(tag_text))
        return ret_val
    
    def paren_full_tag(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["（"]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL) or (self.token.token_type == TokenType.OPEN_PAREN_FULL):
            checkpoint_idx = self.tokenizer.index
            checkpoint_tok = self.token
            ret_val_0 = self.paren_full_inner()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.paren_full_tag()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    ret_val = None
                    break
        if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
            self.tag_buffer = old_buffer
            return None
        self.token = self.tokenizer.get_token()
        self.tag_buffer.append("）")
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "P"))
        elif self.ruby_handler: self.results.append(self.ruby_handler(tag_text))
        return ret_val
    
    def angle_tag(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.ANGLE_LEFT):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["<"]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL) or (self.token.token_type == TokenType.ANGLE_LEFT):
            checkpoint_idx = self.tokenizer.index
            checkpoint_tok = self.token
            ret_val_0 = self.angle_inner()
            if ret_val_0 is not None:
                ret_val = ret_val_0
            else:
                self.tokenizer.index = checkpoint_idx
                self.token = checkpoint_tok
                ret_val_0 = self.angle_tag()
                if ret_val_0 is not None:
                    ret_val = ret_val_0
                else:
                    ret_val = None
                    break
        if (self.token.token_type != TokenType.ANGLE_RIGHT):
            self.tag_buffer = old_buffer
            return None
        self.token = self.tokenizer.get_token()
        self.tag_buffer.append(">")
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "E"))
        return ret_val
    
    def chord_line(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.CHORD_MARK):
            return None
        old_buffer = self.tag_buffer
        self.tag_buffer = ["-"]
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_BRACKET_FULL) or (self.token.token_type == TokenType.CLOSE_BRACKET_FULL) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.ANGLE_LEFT) or (self.token.token_type == TokenType.ANGLE_RIGHT) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL):
            ret_val_0 = self.inner_all()
        tag_text = "".join(self.tag_buffer)
        self.tag_buffer = old_buffer
        self.tag_buffer.append(tag_text)
        if self.tag_handler: self.results.append(self.tag_handler(tag_text, "C"))
        return ret_val
    
    def bracket_inner(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.tag_buffer.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.tag_buffer.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.tag_buffer.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.tag_buffer.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def bracket_full_inner(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.tag_buffer.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.tag_buffer.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.tag_buffer.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.tag_buffer.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.tag_buffer.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def paren_inner(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.tag_buffer.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.tag_buffer.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.tag_buffer.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.tag_buffer.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def paren_full_inner(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.tag_buffer.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.tag_buffer.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.tag_buffer.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.tag_buffer.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.tag_buffer.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def angle_inner(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.tag_buffer.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.tag_buffer.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.tag_buffer.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.tag_buffer.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.tag_buffer.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.tag_buffer.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def inner_all(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.TEXT:
                if (self.token.token_type != TokenType.TEXT):
                    return None
                self.tag_buffer.append(self.token.content)
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.tag_buffer.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.tag_buffer.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.tag_buffer.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.tag_buffer.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.tag_buffer.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.tag_buffer.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.tag_buffer.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.tag_buffer.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.tag_buffer.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.tag_buffer.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.NL:
                if (self.token.token_type != TokenType.NL):
                    return None
                self.tag_buffer.append("\n")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def text_content(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.TEXT):
            return None
        self.results.append(self.token.content)
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def newline(self):
        ret_val_0 = None
        ret_val = True
        if (self.token.token_type != TokenType.NL):
            return None
        self.results.append("\n")
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def other_char(self):
        ret_val_0 = None
        ret_val = True
        match self.token.token_type:
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.results.append("[")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.results.append("]")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_BRACKET_FULL:
                if (self.token.token_type != TokenType.OPEN_BRACKET_FULL):
                    return None
                self.results.append("［")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_BRACKET_FULL:
                if (self.token.token_type != TokenType.CLOSE_BRACKET_FULL):
                    return None
                self.results.append("］")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.results.append("(")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.results.append(")")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.results.append("（")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.results.append("）")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_LEFT:
                if (self.token.token_type != TokenType.ANGLE_LEFT):
                    return None
                self.results.append("<")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.ANGLE_RIGHT:
                if (self.token.token_type != TokenType.ANGLE_RIGHT):
                    return None
                self.tag_buffer.append(">")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.results.append("-")
                self.token = self.tokenizer.get_token()
                ret_val = True
                if ret_val_0 is not None: ret_val = ret_val_0
            case _:
                ret_val = None
        return ret_val
    
    def parse(self):
        ret_val_0 = None
        ret_val = None
        ret_val = self.lyrics()
        return ret_val
    
